### ISSUE TITLE
Reference

### ISSUE THREAD

**Issue by ditafaith** [ZeyuJin/geodetic_inversion#2]
Is there any reference regarding this code ? and also is it possible if only use InSAR results ?

**Comment by ZeyuJin** [comment]
Yes, please add these two references when you use any code or InSAR/GNSS results.

Jin, Z., & Fialko, Y. (2020). Finite slip models of the 2019 Ridgecrest earthquake sequence constrained by space geodetic data and aftershock locations. Bulletin of the Seismological Society of America, 110(4), 1660-1679.

Jin, Z., & Fialko, Y. (2021). Coseismic and early postseismic deformation due to the 2021 M7. 4 Maduo (China) earthquake. Geophysical Research Letters, 48(21), e2021GL095213.

I will also add those citations in the README file.

**Comment by ditafaith** [comment]
Noted. Then, is it possible to get manual and sample to use this code ? Suppose I only have InSAR results.

**Comment by ZeyuJin** [comment]
Yes, this code would help you downsample InSAR results and invert the slip model using Okada's homogeneous solutions. 
When you have the preliminary slip model, you could also use the model to resample your original InSAR data. Such a resampling would skip sampling noisy regions due to tropospheric/ionospheric noise.
Please see the functions "make_insar_data.m" and "resamp_insar_data.m"

Cheers,
Zeyu Jin
